# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('abstract', models.TextField(default=None, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('python', 'python'), ('web development', 'web development'), ('angularJS', 'angularJS'), ('angular', 'angular'), ('engineering', 'engineering'), ('FEA', 'FEA'), ('vibrations', 'vibrations'), ('abaqus', 'abaqus'), ('nastran', 'nastran'), ('matlab', 'matlab')], default='python', max_length=50)),
                ('tags', models.CharField(blank=True, default=None, max_length=1000)),
            ],
        ),
    ]
