# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('subtitle', models.CharField(default=None, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('python', 'python'), ('web development', 'web development'), ('angularJS', 'angularJS'), ('angular', 'angular'), ('engineering', 'engineering'), ('FEA', 'FEA'), ('vibrations', 'vibrations'), ('abaqus', 'abaqus'), ('nastran', 'nastran'), ('matlab', 'matlab')], default='python', max_length=50)),
            ],
        ),
    ]
