# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('image', models.ImageField(upload_to='C:\\Users\\todd\\Projects\\djangoProjects\\mysite\\mysite\\media\\blog_banners', verbose_name='image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
