# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180312_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
